### ISSUE TITLE
UnicodeEncodeError on printing added trend

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/twitterverse#20]
```
Added trend: 29848 | #GoLobos                  -       0 K |    2352824 - Albuquerque.
Added trend: 29849 | #BookLoversDay            -     303 K |    2352824 - Albuquerque.
Added trend: 29850 | #nmwx                     -       0 K |    2352824 - Albuquerque.
Added trend: 29851 | North Korea               -     865 K |    2352824 - Albuquerque.
Added trend: 29852 | Deshaun Watson            -       0 K |    2352824 - Albuquerque.
Added trend: 29853 | #ScentsFromMyChildhood    -       0 K |    2352824 - Albuquerque.
Added trend: 29854 | Jay Bruce                 -       0 K |    2352824 - Albuquerque.
Added trend: 29855 | #Signed                   -       0 K |    2352824 - Albuquerque.
Added trend: 29856 | Joe Webb                  -       0 K |    2352824 - Albuquerque.
Added trend: 29857 | Sonja                     -       0 K |    2352824 - Albuquerque.
Added trend: 29858 | Tom Savage                -       0 K |    2352824 - Albuquerque.
Added trend: 29859 | Ryan Zimmerman            -       0 K |    2352824 - Albuquerque.
Traceback (most recent call last):
  File "./app/utils/insert/trendsCountryAndTowns.py", line 79, in <module>
    main(sys.argv[1:])
  File "./app/utils/insert/trendsCountryAndTowns.py", line 70, in main
    trends.insertTrendsForWoeid(woeid)
  File "/home/MichaelCurrin/apps/twitterverse/app/lib/trends.py", line 61, in insertTrendsForWoeid
    t.place.woeid, t.place.name),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 34: ordinal not in range(128)

2017-08-10 02:07:43 -- Completed task, took 150.00 seconds, return code was 1.
```

**Comment by MichaelCurrin** [comment]
Here is the offending item.
```
>>> db.Trend.get(29860).name
u'Jonathan Garc\xeda'
>>> print _
Jonathan García
```

This prints in my python console though.
